isa-web:
   image: tp33/django:1.2
   external_links:
     - mysql:db
   command: bash -c "git clone https://github.com/Mcronk/project4501.git && cd project4501 && python manage.py migrate && python manage.py runserver"
